package com.pointlessapps.songbook.ui.theme

import androidx.compose.ui.graphics.Color

val darkPrimary = Color(0xffCC9DDB)
val darkOnPrimary = Color(0xff19171A)
val darkSecondary = Color(0xff91C082)
val darkOnSecondary = Color(0xff19171A)
val darkBackground = Color(0xff130418)
val darkOnBackground = Color(0xffffe6ff)
val darkSurface = Color(0xff130418)
val darkOnSurface = Color(0xffffe6ff)
val darkOnSurfaceVariant = Color(0xffcc9ddb)
val darkError = Color(0xffC64832)
val darkOnError = Color(0xffffe6ff)
val darkOutline = Color(0xff573B60)
val darkOutlineVariant = Color(0xff3C2144)
val darkSurfaceContainer = Color(0xff130418)
val darkSurfaceContainerHigh = Color(0xff1f0e24)
val darkSurfaceContainerLow = Color(0xff08000d)
val darkPrimaryContainer = Color(0xff503759)
val darkOnPrimaryContainer = Color(0xffEDC8F7)
val darkInverseSurface = Color(0xffE7E0E8)
val darkInverseOnSurface = Color(0xff312E33)

val lightPrimary = Color(0xff7A5B83)
val lightOnPrimary = Color(0xffFFFFFF)
val lightSecondary = Color(0xff426938)
val lightOnSecondary = Color(0xffFFFFFF)
val lightBackground = Color(0xffFFF7FF)
val lightOnBackground = Color(0xff1F1A20)
val lightSurface = Color(0xffFFF7FF)
val lightOnSurface = Color(0xff1F1A20)
val lightOnSurfaceVariant = Color(0xff4D444F)
val lightError = Color(0xffBA1A1A)
val lightOnError = Color(0xffFFFFFF)
val lightOutline = Color(0xff7F7481)
val lightOutlineVariant = Color(0xffD0C3D2)
val lightSurfaceContainer = Color(0xffF9EEFA)
val lightSurfaceContainerHigh = Color(0xffF3E8F4)
val lightSurfaceContainerLow = Color(0xffFFF7FF)
val lightPrimaryContainer = Color(0xffF7D8FF)
val lightOnPrimaryContainer = Color(0xff2F1138)
val lightInverseSurface = Color(0xff342F35)
val lightInverseOnSurface = Color(0xffF7EEF6)
