package com.pointlessapps.songbook.ui.theme

import androidx.compose.ui.graphics.Color

internal val darkPrimary = Color(0xffCC9DDB)
internal val darkOnPrimary = Color(0xff19171A)
internal val darkSecondary = Color(0xff91C082)
internal val darkOnSecondary = Color(0xff19171A)
internal val darkBackground = Color(0xff130418)
internal val darkOnBackground = Color(0xffffe6ff)
internal val darkSurface = Color(0xff130418)
internal val darkOnSurface = Color(0xffffe6ff)
internal val darkOnSurfaceVariant = Color(0xffcc9ddb)
internal val darkError = Color(0xffC64832)
internal val darkOnError = Color(0xffffe6ff)
internal val darkOutline = Color(0xff573B60)
internal val darkOutlineVariant = Color(0xff3C2144)
internal val darkSurfaceContainer = Color(0xff130418)
internal val darkSurfaceContainerHigh = Color(0xff1f0e24)
internal val darkSurfaceContainerLow = Color(0xff08000d)
internal val darkPrimaryContainer = Color(0xff503759)
internal val darkOnPrimaryContainer = Color(0xffEDC8F7)
internal val darkInverseSurface = Color(0xffE7E0E8)
internal val darkInverseOnSurface = Color(0xff312E33)

internal val lightPrimary = Color(0xff7A5B83)
internal val lightOnPrimary = Color(0xffFFFFFF)
internal val lightSecondary = Color(0xff426938)
internal val lightOnSecondary = Color(0xffFFFFFF)
internal val lightBackground = Color(0xffFFF7FF)
internal val lightOnBackground = Color(0xff1F1A20)
internal val lightSurface = Color(0xffFFF7FF)
internal val lightOnSurface = Color(0xff1F1A20)
internal val lightOnSurfaceVariant = Color(0xff4D444F)
internal val lightError = Color(0xffBA1A1A)
internal val lightOnError = Color(0xffFFFFFF)
internal val lightOutline = Color(0xff7F7481)
internal val lightOutlineVariant = Color(0xffD0C3D2)
internal val lightSurfaceContainer = Color(0xffF9EEFA)
internal val lightSurfaceContainerHigh = Color(0xffF3E8F4)
internal val lightSurfaceContainerLow = Color(0xffFFF7FF)
internal val lightPrimaryContainer = Color(0xffF7D8FF)
internal val lightOnPrimaryContainer = Color(0xff2F1138)
internal val lightInverseSurface = Color(0xff342F35)
internal val lightInverseOnSurface = Color(0xffF7EEF6)
